import Foundation
import Observation
import SwiftUI

/// State for the hub's Plans pane. Summaries list every version; full
/// plans load per id on demand. A plan_ready event from the conversation
/// upserts live, so a plan generated by voice appears while the pane is
/// open.
@MainActor
@Observable
final class PlansModel {

    private(set) var summaries: [PlanSummary] = []
    private(set) var details: [String: Plan] = [:]
    private(set) var isLoading = false
    private(set) var errorText: String?

    private let auth: any AuthProvider

    init(auth: any AuthProvider) {
        self.auth = auth
    }

    // MARK: - Grouping

    /// Active plans, one per domain, newest first (summaries arrive sorted).
    var activePlans: [PlanSummary] {
        summaries.filter { $0.status == .active }
    }

    /// The version chain for an active plan: newest → oldest, following
    /// supersedes pointers. Cycle-guarded; a broken link ends the chain.
    static func versionChain(activeId: String, summaries: [PlanSummary]) -> [PlanSummary] {
        let byId = Dictionary(summaries.map { ($0.id, $0) }, uniquingKeysWith: { first, _ in first })
        var chain: [PlanSummary] = []
        var visited = Set<String>()
        var cursor: String? = activeId
        while let id = cursor, !visited.contains(id), let summary = byId[id] {
            visited.insert(id)
            chain.append(summary)
            cursor = summary.supersedes
        }
        return chain
    }

    func chain(for active: PlanSummary) -> [PlanSummary] {
        Self.versionChain(activeId: active.id, summaries: summaries)
    }

    /// 1-indexed week the user is in, clamped to the plan's span. Mirrors
    /// the server's planWeek.
    static func week(of summary: PlanSummary, now: Date) -> Int {
        let elapsedDays = Int(now.timeIntervalSince(summary.createdAt) / 86_400)
        let week = max(0, elapsedDays) / 7 + 1
        return min(week, max(1, (summary.meta.horizonDays + 6) / 7))
    }

    static func weekCount(horizonDays: Int) -> Int {
        max(1, (horizonDays + 6) / 7)
    }

    // MARK: - Loading and live updates

    func load() async {
        guard let client = makeClient() else { return }
        isLoading = true
        errorText = nil
        defer { isLoading = false }
        do {
            summaries = try await client.listPlans()
        } catch {
            errorText = error.localizedDescription
        }
    }

    func loadDetail(id: String) async {
        guard details[id] == nil, let client = makeClient() else { return }
        do {
            details[id] = try await client.planDetail(id: id)
        } catch {
            errorText = error.localizedDescription
        }
    }

    /// A plan_ready event from the conversation — the new version becomes
    /// the pane's truth without a refetch round trip.
    func apply(_ plan: Plan) {
        withAnimation(.snappy) {
            details[plan.id] = plan
            let summary = PlanSummary(
                id: plan.id,
                meta: plan.meta,
                status: plan.status,
                supersedes: plan.supersedes,
                sessionCount: plan.sessions.count,
                scheduleEntryCount: plan.schedule.count,
                createdAt: plan.createdAt
            )
            // Mirror the server's supersede rules locally: an adaptation
            // retires its predecessor; a fresh generation retires whatever
            // was active in the domain. Retired summaries stay listed —
            // they are the history.
            for index in summaries.indices {
                let retiredByAdaptation = summaries[index].id == plan.supersedes
                let retiredByNewPlan =
                    plan.supersedes == nil
                    && summaries[index].status == .active
                    && summaries[index].meta.domain == plan.meta.domain
                if retiredByAdaptation || retiredByNewPlan {
                    summaries[index].status = .superseded
                }
            }
            summaries.removeAll { $0.id == plan.id }
            summaries.insert(summary, at: 0)
        }
    }

    private func makeClient() -> APIClient? {
        let urlString =
            UserDefaults.standard.string(forKey: DebugModel.serverURLKey) ?? "http://localhost:8080"
        guard let url = URL(string: urlString), url.scheme != nil else {
            errorText = "Invalid server URL."
            return nil
        }
        guard auth.currentUserId != nil else {
            errorText = "Sign in to see your plans."
            return nil
        }
        return APIClient(baseURL: url, auth: auth)
    }
}
